### ISSUE TITLE
Question about the use of 0x00 and 0x82 in the sendBuffer for setting LCD screen brightness

### ISSUE THREAD

**Issue by hayschan** [dwinhmi/DWIN_DGUS_HMI#5]
I am currently reviewing the code in your repository and came across a specific code snippet related to setting the brightness of an LCD screen. I have a few questions regarding the usage of `0x00` and `0x82` in the `sendBuffer` array. Additionally, I would like to know if these values are documented and, if so, which documentation includes them.

Here is the code in question:

https://github.com/dwinhmi/DWIN_DGUS_HMI/blob/ae75ddad21a0110fb5e8b84a58ce1244c7d82d92/src/DWIN.cpp#L74-L79

My specific questions are:

1. What is the purpose or significance of using `0x00` and `0x82` in the `sendBuffer` array?
2. Are these values (`0x00` and `0x82`) necessary for setting the brightness of the LCD screen? If so, what role do they play?
3. Is there any documentation that explains the use of these values in the context of setting LCD screen brightness?

I appreciate any clarification you can provide on this matter. Thank you for your time and contribution to the repository.

**Comment by dwinhmi** [comment]
0x0082 is the memory address of Brightness regsiter 
![IMG_20230523_114009.jpg](https://github.com/dwinhmi/DWIN_DGUS_HMI/assets/106271456/59174806-6fb9-4d50-8d37-390f9ab406aa)

You can refer the Development Guide for deep understanding

https://www.dwin-global.com/uploads/T5L_DGUSII-Application-Development-Guide-V2.6.pdf

**Comment by dwinhmi** [comment]
Closing the thread as it's not an issue
